name: Build and Test

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v2
      - name: Download Sqlite3
        run: sudo apt-get install libsqlite3-dev
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
